# Generated by Django 4.0.5 on 2022-07-29 14:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists Mofo.'}, help_text='Required. 150 characters or fewer. Only alphanumeric characters are allowed.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric character are allowed')], verbose_name='username'),
        ),
    ]
