# Generated by Django 4.0.5 on 2022-09-26 01:07

import codify.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codify.language')),
            ],
        ),
        migrations.CreateModel(
            name='Subtopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='codify.topic')),
            ],
        ),
        migrations.CreateModel(
            name='Snipped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('xtitle', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('ytitle', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('text', models.CharField(blank=True, max_length=300, null=True)),
                ('xtext', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('ytext', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('background', models.IntegerField(default=0)),
                ('code', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(default='snippets/default.jpg', upload_to=codify.models.user_directory_path)),
                ('twitter', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codify.language')),
                ('subtopic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='codify.subtopic')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='codify.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
