# Generated by Django 4.0.5 on 2022-07-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codify', '0002_alter_subtopic_topic_alter_topic_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='snipped',
            name='highlighted',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
