# Generated by Django 4.0.5 on 2022-07-30 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codify', '0003_snipped_highlighted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codify.language'),
        ),
    ]
