# Generated by Django 4.0.5 on 2022-08-01 18:09

import codify.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codify', '0004_alter_topic_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twitter',
            old_name='name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='snipped',
            name='highlighted',
        ),
        migrations.AddField(
            model_name='snipped',
            name='image',
            field=models.ImageField(default='snippets/default.jpg', upload_to=codify.models.user_directory_path),
        ),
    ]
