# Generated by Django 4.0.5 on 2022-08-06 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codify', '0005_rename_name_twitter_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitter',
            name='image',
        ),
        migrations.AddField(
            model_name='snipped',
            name='xtext',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='snipped',
            name='xtitle',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='snipped',
            name='ytext',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='snipped',
            name='ytitle',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='snipped',
            name='subtopic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='codify.subtopic'),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='codify.topic'),
        ),
        migrations.AlterField(
            model_name='twitter',
            name='alias',
            field=models.TextField(),
        ),
    ]
