# Generated by Django 4.0.5 on 2022-08-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codify', '0006_remove_twitter_image_snipped_xtext_snipped_xtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='snipped',
            name='xtwitter',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='snipped',
            name='ytwitter',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
