# Generated by Django 4.0.5 on 2022-08-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codify', '0007_snipped_xtwitter_snipped_ytwitter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snipped',
            name='xtwitter',
        ),
        migrations.RemoveField(
            model_name='snipped',
            name='ytwitter',
        ),
        migrations.AlterField(
            model_name='snipped',
            name='twitter',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Twitter',
        ),
    ]
