# Generated by Django 4.0.5 on 2022-08-09 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codify', '0008_remove_snipped_xtwitter_remove_snipped_ytwitter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snipped',
            name='description',
        ),
        migrations.AlterField(
            model_name='snipped',
            name='subtopic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='codify.subtopic'),
        ),
        migrations.AlterField(
            model_name='snipped',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='codify.topic'),
        ),
    ]
