# Generated by Django 4.0.5 on 2022-08-10 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codify', '0009_remove_snipped_description_alter_snipped_subtopic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='snipped',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='snipped',
            name='text',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='snipped',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
