# Generated by Django 4.0.5 on 2022-08-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codify', '0010_snipped_code_alter_snipped_text_alter_snipped_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snipped',
            name='xtext',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='snipped',
            name='xtitle',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='snipped',
            name='ytext',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='snipped',
            name='ytitle',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
