# Generated by Django 4.0.5 on 2022-08-29 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codify', '0011_alter_snipped_xtext_alter_snipped_xtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snipped',
            name='xtext',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='snipped',
            name='xtitle',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='snipped',
            name='ytext',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='snipped',
            name='ytitle',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True),
        ),
    ]
